use medicalsystem;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS chat_history;
DROP TABLE IF EXISTS dispatches;
DROP TABLE IF EXISTS staffs;
DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS ambulances;
DROP TABLE IF EXISTS patients;
SET FOREIGN_KEY_CHECKS = 1;